# Generated by Django 4.2.2 on 2023-06-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_auto_20210511_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
