# Generated by Django 4.2.2 on 2023-06-15 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_department_id_alter_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="创建时间",
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="creator",
            field=models.CharField(
                blank=True, help_text="创建人", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="is_deleted",
            field=models.CharField(default=0, help_text="是否删除", max_length=36),
        ),
        migrations.AddField(
            model_name="department",
            name="update_at",
            field=models.DateTimeField(
                auto_now=True, help_text="修改时间", verbose_name="修改时间"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="updater",
            field=models.CharField(
                blank=True, help_text="修改人", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="创建时间",
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="creator",
            field=models.CharField(
                blank=True, help_text="创建人", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_deleted",
            field=models.CharField(default=0, help_text="是否删除", max_length=36),
        ),
        migrations.AddField(
            model_name="employee",
            name="update_at",
            field=models.DateTimeField(
                auto_now=True, help_text="修改时间", verbose_name="修改时间"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="updater",
            field=models.CharField(
                blank=True, help_text="修改人", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
