# Generated by Django 4.2.2 on 2023-08-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_department_create_at_department_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
