name: Django Test

on: [ push, pull_request ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, '3.10', 3.11 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Run Tests
        run: |
          # python manage.py test
          coverage run --source='.' manage.py test
      - name: Generate coverage xml report
        run: coverage xml
      - name: Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          slug: lihuacai168/django-ninja-demo
          # User defined upload name. Visible in Codecov UI
          name: django-ninja-demo
          # Repository upload token - get it from codecov.io
          token: ${{ secrets.CODECOV_TOKEN }}
          # Path to coverage file to upload
          file: ./coverage.xml
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: unittests
          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: true